### ISSUE TITLE
Replacing the configuration

### ISSUE THREAD

**Issue by rettenbs** [napalm-automation-community/napalm-arubaos-switch#13]
## Expected Behavior
Executing `compare_config` after `load_replace_candidate` returns a list of added/removed configuration values.

## Actual Behavior
Executing `compare_config` after `load_replace_candidate` always returns a empty list.

## Steps to Reproduce the Problem

  1. Create a configuration that differs from the current configuration of the switch
  2. Configure task with nornir and nornir napalm plugin: https://github.com/nornir-automation/nornir_napalm/blob/master/nornir_napalm/plugins/tasks/napalm_configure.py
  3.  Alternatively, manually execute the steps in the task.

## Specifications

  - Version: napalm-arubaos-switch - latest development branch
  - Platform: Switch - HP2920-48G-POE+
  - Subsystem:

## Analysis

I think the issue is here: https://github.com/napalm-automation-community/napalm-arubaos-switch/blob/development/napalm_arubaoss/helper/compare_config.py

The switch requires some time to compute the difference. If I add a sleep time between the two API calls in the function, everything works as expected. Currently, 2 sec seems to be enough.

Unfortunately, I have not found a way to check whether the diff is ready. On our switch, the rest API `system/config/cfg_restore/latest_diff` always returns a status `CRS_IN_PROGRESS` but never `CRS_SUCCESS`.

Is it possible to add an optional argument to specify a sleep time for the compare_config function?

**Comment by hupebln** [comment]
Thanks for giving a heads up.

We faced the same behavior in our test environment as well and it looks like it is caused by using requests-futures.
The idea was to speed up the communication to the devices by using asynchronous calls. Requests-Futures shares the same session object through all future instances.
The problem here is most likely with the ArubaOS devices, as it looks like you cannot/should not use the same session to do multiple calls.

Other faced the same issue already and discussed it [here](https://community.arubanetworks.com/community-home/digestviewer/viewthread?MID=28798#bme4aa3703-e476-4880-9cb4-9b208f86b2f4).
Our plan for the future is to revert the connection part back to Python-Requests and set **keep_alive** to **False**.

Have you tested it also with the release 0.1.1? And have you experienced the same?

**Comment by hupebln** [comment]
quick update:
I re-implemented python requests in a local branch and tested it again. I see the same issue appearing.

I've then tested to implement a sleep between the calls and it works (like @rettenbs mentioned). But as we don't know how long it exactly takes and each device could take more or less time, I'd suggest to implement a loop with 5 rounds and wait 1 second between the loop steps. So that it would wait 5 seconds max and return before if it found anything.
